version: "3.8"

services:
  pharma-analysis:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
    environment:
      - DATA_PATH=/app/data/Pharma_Drug_Sales.csv
      - FLASK_ENV=development
